language: python
python:
  - 3.6
  - 3.7
install:
  - pipenv install --dev
script:
  - inv cover qa
after_success:
  - pip install coveralls
  - coveralls --rcfile=coverage.rc
  - ./travis-bench-after-success.sh
